### ISSUE TITLE
room temperature show 0°

### ISSUE THREAD

**Issue by bilou95** [kinou74/Domoticz-Palazzetti#5]
Thanks you for your work.
I have a Cbox with version 2.4.1 connected to a palazzetti Ines.
I was able to get most of the predefine variable and also able to start/stop the heater with success.
I got also by example the status and number of consumed pellet.

but the room temperature is not showed.
Do you have any advice ?
![retreived informations](https://user-images.githubusercontent.com/76478205/103248761-671a3b00-496c-11eb-9459-c8d26da1dcc5.jpg)

**Comment by vfd7** [comment]
Hi Bilou95,

I have the same issue. 
Did you succeed to solve the issue since then?

Thx.
vfd7

**Comment by skarab22** [comment]
At the line 115 :
`"TMP_ROOM": "T5"` I replace T5 by T1. You can verify the value by consulting .lua command : 
CBOX_IP/cgi-bin/sendmsg.lua?cmd=GET+ALLS and then searching the value indicated on the stove's screen.

**Comment by vfd7** [comment]
Skarab22,

Thank you very much for your reply. I just did the fix and it works perfectly.

Thx.
vfd7.

**Comment by bilou95** [comment]
Perfect. Thanks you so much Skarab22, It's effecitvely solve the issue. 
I have the right value now.
